'use client';

import type { CSSProperties } from 'react';

/**
 * Aurora — a soft, brand-tinted mesh-gradient atmosphere behind the hero.
 *
 * Uses Limud's OWN brand hues (blue #3b82f6 + fuchsia #d946ef + indigo #6366f1
 * + a sky accent) — desaturated, soft, layered — NOT generic "AI-purple slop".
 *
 * v17.15 FIX: the blob size/position/blur are now INLINE styles, not Tailwind
 * arbitrary-value classes (`h-[55vh]` etc.). Those arbitrary classes were not
 * being generated by Tailwind for this file, so every blob rendered 0×0 and the
 * whole aurora was invisible — the real reason "you can barely see the effects".
 * Inline styles can't be tree-shaken away, so the atmosphere always renders.
 *
 * Performance/a11y: compositor-only drift (transform), pointer-events-none,
 * gated behind prefers-reduced-motion — reduced-motion users get a still (but
 * now genuinely visible) gradient.
 */

type AuroraProps = {
  /** Extra classes for positioning (defaults to full-bleed absolute). */
  className?: string;
  /** 0–1 overall strength. Default 1. Lower for dense sections. */
  intensity?: number;
};

type Blob = { size: string; bg: string; delay: string; pos: CSSProperties };

const BLOBS: Blob[] = [
  {
    size: '64vh',
    delay: '0s',
    bg: 'radial-gradient(circle at 50% 50%, rgb(59 130 246 / 0.55), rgb(59 130 246 / 0.18) 45%, transparent 72%)',
    pos: { left: '-12%', top: '-22%' },
  },
  {
    size: '56vh',
    delay: '-6s',
    bg: 'radial-gradient(circle at 50% 50%, rgb(217 70 239 / 0.42), rgb(217 70 239 / 0.14) 45%, transparent 72%)',
    pos: { right: '-10%', top: '2%' },
  },
  {
    size: '58vh',
    delay: '-12s',
    bg: 'radial-gradient(circle at 50% 50%, rgb(99 102 241 / 0.40), rgb(99 102 241 / 0.12) 45%, transparent 72%)',
    pos: { left: '24%', top: '40%' },
  },
  {
    size: '44vh',
    delay: '-18s',
    bg: 'radial-gradient(circle at 50% 50%, rgb(56 189 248 / 0.34), transparent 70%)',
    pos: { right: '16%', top: '-12%' },
  },
];

// Fine grain to kill gradient banding and add a premium tactile finish.
const GRAIN =
  "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='120' height='120'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='2'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='0.5'/%3E%3C/svg%3E\")";

export default function Aurora({ className = '', intensity = 1 }: AuroraProps) {
  return (
    <div
      aria-hidden
      className={`aurora pointer-events-none absolute inset-0 -z-10 overflow-hidden ${className}`}
      style={{ opacity: intensity }}
    >
      {BLOBS.map((b, i) => (
        <div
          key={i}
          className="aurora-blob"
          style={{
            position: 'absolute',
            width: b.size,
            height: b.size,
            borderRadius: '9999px',
            filter: 'blur(72px)',
            background: b.bg,
            animationDelay: b.delay,
            willChange: 'transform',
            ...b.pos,
          }}
        />
      ))}
      <div
        style={{
          position: 'absolute',
          inset: 0,
          opacity: 0.15,
          mixBlendMode: 'soft-light',
          backgroundImage: GRAIN,
        }}
      />
    </div>
  );
}
